---
apiVersion: v1 
kind: Secret 
metadata:
  labels:
    app: cloudtruth-with-argo-cd-and-helm-stringdata
  name: cloudtruth-with-argo-cd-and-helm-stringdata
stringData:
   FLASK_APP: {{ .Values.configMap.flask.app | quote }}
---
apiVersion: v1 
kind: Secret 
metadata:
  labels:
    app: cloudtruth-with-argo-cd-and-helm-data
  name: cloudtruth-with-argo-cd-and-helm-data
data:
   FLASK_APP: {{ .Values.configMap.flask.app | b64enc | quote }}
