---
apiVersion: v1 
kind: Secret 
metadata:
  labels:
    app: cloudtruth-with-argo-cd-and-helm
  name: cloudtruth-with-argo-cd-and-helm
data:
   FLASK_APP: {{ .Values.configMap.flask.app | b64enc | quote }}
