---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudtruth-with-argo-cd-and-helm
  name: cloudtruth-with-argo-cd-and-helm
spec:
  selector:
    app: cloudtruth-with-argo-cd-and-helm
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
