---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudtruth-with-argo-cd-and-helm
spec:
  project: cloudtruth
  source:
    repoURL: https://github.com/cloud37/cloudtruth.git
    targetRevision: main
    path: apps/cloudtruth-with-argo-cd-and-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudtruth
